import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login your account | Dynamic Med",
  description: "Generated by create next app",
};

export default function CategoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
