import ScrollTop from "@/components/Buttons/ScrollTop";

import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Products | Seacoast Surgical",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div>
        {children}</div>
      <div className="z-50 fixed bottom-5 right-5  ">
        <ScrollTop/>
      </div>
    </div>
  );
}
